### PR TITLE
Issue/133

### PR DESCRIPTION
**Pull request by codewizard870**

### CODE REVIEW

**Comment by markots** [comment]
Please delete empty space, it need to be full screen 
Screenshot 2023-08-10 alle 18 21 16

**Comment by markots** [comment]
Also, please use the frame that I separated from the mobile mockup
image

**Comment by d2Dreamer** [comment]
I think this looks good, one thing i'd consider is making the scroll achievable by drag/grab.

**Comment by d2Dreamer** [comment]
Added 2 of the remaining 3. Additional change spotted - the background of the content is clear, as well as the container, meaning we can see the back of the site. This could do with a phone border & background to sit on @markots .

**Comment by d2Dreamer** [comment]
Added last one with temporary values - code is clunky.

**Review by markots — CHANGES_REQUESTED** [review]
- Floating "create post" btn is behind the scrolling posts on the feed. need to be in front
Screenshot 2023-08-11 alle 09 02 27

- Add border outline for mockups 2,3 and 4
Screenshot 2023-08-11 alle 09 02 08

**Comment by markots** [comment]
ADDITIONAL IMPROVEMENT 

Please add scrollable hone mockup on the home screen.

Figma
https://www.figma.com/file/dgoMR41ZabUnJxVeYPq3Rd/Landing-page?type=design&node-id=1755%3A74232&mode=design&t=F7V85RUTguyYc0S1-1

**Comment by d2Dreamer** [comment]
All appears fixed. Pushing now.

**Pull request merged**
